[package]
name = "ephemeral-vrf-oracle"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ephemeral_vrf"
path = "main.rs"

[dependencies]
ephemeral-vrf = { workspace = true }
solana-sdk.workspace = true