[package]
name = "ephemeral-vrf-oracle"
version = {workspace = true}
edition = {workspace = true}

[[bin]]
name = "ephemeral_vrf"
path = "main.rs"

[dependencies]
ephemeral-vrf = { workspace = true }
solana-sdk.workspace = true