[package]
name = "ephemeral-vrf-oracle"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ephemeral_vrf"
path = "main.rs"

[dependencies]
curve25519-dalek.workspace = true
solana-sdk.workspace = true
sha2.workspace = true
hkdf.workspace = true